apiVersion: v1
kind: Namespace
metadata:
  name: boostflow
  labels:
    app.kubernetes.io/part-of: boostflow
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: boostflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/part-of: boostflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: boostflow
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: monitoring
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: security
automountServiceAccountToken: false

