apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: boostflow-runtime-minio
  namespace: boostflow
spec:
  type: kv-v2
  mount: secret
  path: boostflow/runtime/minio
  refreshAfter: 1h
  vaultAuthRef: boostflow-auth
  destination:
    name: boostflow-minio-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        MINIO_ENDPOINT: { text: '{{ .Secrets.endpoint }}' }
        MINIO_EXTERNAL_ENDPOINT: { text: '{{ .Secrets.external_endpoint }}' }
        MINIO_PORT: { text: '{{ .Secrets.port }}' }
        MINIO_ROOT_USER: { text: '{{ .Secrets.root_user }}' }
        MINIO_ROOT_PASSWORD: { text: '{{ .Secrets.root_password }}' }
        MINIO_USE_SSL: { text: '{{ .Secrets.use_ssl }}' }
        MINIO_PROFILE_PICTURES_BUCKET: { text: '{{ .Secrets.profile_pictures_bucket }}' }
        MINIO_PROJECT_DOCUMENTS_BUCKET: { text: '{{ .Secrets.project_documents_bucket }}' }
