apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: boostflow-runtime-ghcr
  namespace: boostflow
spec:
  type: kv-v2
  mount: secret
  path: boostflow/runtime/ghcr
  refreshAfter: 1h
  vaultAuthRef: boostflow-auth
  destination:
    name: ghcr-pull-secret
    create: true
    overwrite: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        .dockerconfigjson:
          text: |
            {"auths":{"ghcr.io":{"username":"{{ .Secrets.username }}","password":"{{ .Secrets.password }}","auth":"{{ printf "%s:%s" .Secrets.username .Secrets.password | b64enc }}"}}}
