apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-vault
  namespace: monitoring
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: monitoring-vault
  namespace: monitoring
spec:
  address: http://vault.vault.svc:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: monitoring-auth
  namespace: monitoring
spec:
  vaultConnectionRef: monitoring-vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: monitoring-grafana
    serviceAccount: monitoring-vault
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: monitoring-grafana
  namespace: monitoring
spec:
  type: kv-v2
  mount: secret
  path: monitoring/grafana
  refreshAfter: 1h
  vaultAuthRef: monitoring-auth
  destination:
    name: grafana-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        admin-password:
          text: '{{ .Secrets.admin_password }}'
