apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: monitoring-basic-auth
  namespace: monitoring
spec:
  type: kv-v2
  mount: secret
  path: monitoring/kibana
  refreshAfter: 1h
  vaultAuthRef: monitoring-auth
  destination:
    name: monitoring-basic-auth
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        auth:
          text: '{{ .Secrets.htpasswd }}'
