apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boostflow-neuvector
  namespace: argocd
spec:
  project: boostflow
  source:
    repoURL: https://neuvector.github.io/neuvector-helm/
    chart: core
    targetRevision: 2.9.10
    helm:
      releaseName: neuvector
      values: |
        leastPrivilege: true
        controller:
          replicas: 1
          pvc:
            enabled: true
            accessModes:
              - ReadWriteOnce
            storageClass: "local-path"
            capacity: 1Gi
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
        enforcer:
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        manager:
          svc:
            type: ClusterIP
        cve:
          scanner:
            replicas: 1
          updater:
            image:
              repository: neuvector/updater
              tag: latest
        k3s:
          enabled: false
        containerd:
          enabled: true
          path: /run/containerd/containerd.sock
        psp: false
        internal:
          autoGenerateCert: true
        certupgrader:
          activeDeadlineSeconds: 600
        crdwebhook:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: neuvector-internal-certs
      namespace: security
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
