apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boostflow-monitoring
  namespace: argocd
spec:
  project: boostflow
  source:
    repoURL: https://github.com/KDim67/boostflow-thesis-config.git
    targetRevision: main
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
